development:
  auth0_client_id: <%= ENV["PHC_DEV_AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["PHC_DEV_AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["PHC_DEV_AUTH0_DOMAIN"] %>

test:
  auth0_client_id: <%= ENV["PHC_DEV_AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["PHC_DEV_AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["PHC_DEV_AUTH0_DOMAIN"] %>

production:
  auth0_client_id: <%= ENV["PHC_DEV_AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["PHC_DEV_AUTH0_CLIENT_SECRET"] %>
  auth0_domain: <%= ENV["PHC_DEV_AUTH0_DOMAIN"] %>